# Generated by Django 3.2.7 on 2021-09-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='postandcomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(default='', max_length=2000)),
                ('comment', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
