# Generated by Django 3.2.7 on 2021-09-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_auto_20210924_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postandcomment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
